#!/bin/sh
# Mongo C Driver uninstall program, generated on Tue Apr 28 15:36:29 PDT 2020

# Copyright 2018-present MongoDB, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

save_pwd=$(pwd)
cd /opt/splunk-home/

printf "Removing file "lib/libbson-1.0.so.0.0.0""
(rm -f "lib/libbson-1.0.so.0.0.0" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libbson-1.0.so.0""
(rm -f "lib/libbson-1.0.so.0" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libbson-1.0.so""
(rm -f "lib/libbson-1.0.so" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libbson-static-1.0.a""
(rm -f "lib/libbson-static-1.0.a" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-config.h""
(rm -f "include/libbson-1.0/bson/bson-config.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-version.h""
(rm -f "include/libbson-1.0/bson/bson-version.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bcon.h""
(rm -f "include/libbson-1.0/bson/bcon.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-atomic.h""
(rm -f "include/libbson-1.0/bson/bson-atomic.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-clock.h""
(rm -f "include/libbson-1.0/bson/bson-clock.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-compat.h""
(rm -f "include/libbson-1.0/bson/bson-compat.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-context.h""
(rm -f "include/libbson-1.0/bson/bson-context.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-decimal128.h""
(rm -f "include/libbson-1.0/bson/bson-decimal128.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-endian.h""
(rm -f "include/libbson-1.0/bson/bson-endian.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-error.h""
(rm -f "include/libbson-1.0/bson/bson-error.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson.h""
(rm -f "include/libbson-1.0/bson/bson.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-iter.h""
(rm -f "include/libbson-1.0/bson/bson-iter.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-json.h""
(rm -f "include/libbson-1.0/bson/bson-json.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-keys.h""
(rm -f "include/libbson-1.0/bson/bson-keys.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-macros.h""
(rm -f "include/libbson-1.0/bson/bson-macros.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-md5.h""
(rm -f "include/libbson-1.0/bson/bson-md5.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-memory.h""
(rm -f "include/libbson-1.0/bson/bson-memory.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-oid.h""
(rm -f "include/libbson-1.0/bson/bson-oid.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-reader.h""
(rm -f "include/libbson-1.0/bson/bson-reader.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-string.h""
(rm -f "include/libbson-1.0/bson/bson-string.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-types.h""
(rm -f "include/libbson-1.0/bson/bson-types.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-utf8.h""
(rm -f "include/libbson-1.0/bson/bson-utf8.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-value.h""
(rm -f "include/libbson-1.0/bson/bson-value.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-version-functions.h""
(rm -f "include/libbson-1.0/bson/bson-version-functions.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson/bson-writer.h""
(rm -f "include/libbson-1.0/bson/bson-writer.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libbson-1.0/bson.h""
(rm -f "include/libbson-1.0/bson.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/pkgconfig/libbson-1.0.pc""
(rm -f "lib/pkgconfig/libbson-1.0.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/pkgconfig/libbson-static-1.0.pc""
(rm -f "lib/pkgconfig/libbson-static-1.0.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/libbson-1.0/libbson-1.0-config.cmake""
(rm -f "lib/cmake/libbson-1.0/libbson-1.0-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/libbson-1.0/libbson-1.0-config-version.cmake""
(rm -f "lib/cmake/libbson-1.0/libbson-1.0-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/libbson-static-1.0/libbson-static-1.0-config.cmake""
(rm -f "lib/cmake/libbson-static-1.0/libbson-static-1.0-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/libbson-static-1.0/libbson-static-1.0-config-version.cmake""
(rm -f "lib/cmake/libbson-static-1.0/libbson-static-1.0-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libmongoc-1.0.so.0.0.0""
(rm -f "lib/libmongoc-1.0.so.0.0.0" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libmongoc-1.0.so.0""
(rm -f "lib/libmongoc-1.0.so.0" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libmongoc-1.0.so""
(rm -f "lib/libmongoc-1.0.so" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libmongoc-1.0.so.0.0.0""
(rm -f "lib/libmongoc-1.0.so.0.0.0" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libmongoc-1.0.so.0""
(rm -f "lib/libmongoc-1.0.so.0" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libmongoc-1.0.so""
(rm -f "lib/libmongoc-1.0.so" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libmongoc-static-1.0.a""
(rm -f "lib/libmongoc-static-1.0.a" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-config.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-config.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-version.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-version.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-apm.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-apm.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-bulk-operation.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-bulk-operation.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-change-stream.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-change-stream.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-client.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-client.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-client-pool.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-client-pool.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-collection.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-collection.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-cursor.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-cursor.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-database.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-database.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-error.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-error.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-flags.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-flags.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-find-and-modify.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-find-and-modify.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-gridfs.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-gridfs.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-gridfs-file.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-gridfs-file.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-gridfs-file-page.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-gridfs-file-page.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-gridfs-file-list.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-gridfs-file-list.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-handshake.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-handshake.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-host-list.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-host-list.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-init.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-init.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-index.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-index.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-iovec.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-iovec.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-log.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-log.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-macros.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-macros.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-matcher.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-matcher.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-opcode.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-opcode.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-read-concern.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-read-concern.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-read-prefs.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-read-prefs.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-server-description.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-server-description.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-client-session.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-client-session.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-socket.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-socket.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-stream-tls-libressl.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-tls-libressl.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-stream-tls-openssl.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-tls-openssl.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-stream.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-stream-buffered.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-buffered.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-stream-file.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-file.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-stream-gridfs.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-gridfs.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-stream-socket.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-socket.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-topology-description.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-topology-description.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-uri.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-uri.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-version-functions.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-version-functions.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-write-concern.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-write-concern.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-rand.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-rand.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-stream-tls.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-tls.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc/mongoc-ssl.h""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-ssl.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/libmongoc-1.0/mongoc.h""
(rm -f "include/libmongoc-1.0/mongoc.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/pkgconfig/libmongoc-1.0.pc""
(rm -f "lib/pkgconfig/libmongoc-1.0.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/pkgconfig/libmongoc-static-1.0.pc""
(rm -f "lib/pkgconfig/libmongoc-static-1.0.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/pkgconfig/libmongoc-ssl-1.0.pc""
(rm -f "lib/pkgconfig/libmongoc-ssl-1.0.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/libmongoc-1.0/libmongoc-1.0-config.cmake""
(rm -f "lib/cmake/libmongoc-1.0/libmongoc-1.0-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/libmongoc-1.0/libmongoc-1.0-config-version.cmake""
(rm -f "lib/cmake/libmongoc-1.0/libmongoc-1.0-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/libmongoc-static-1.0/libmongoc-static-1.0-config.cmake""
(rm -f "lib/cmake/libmongoc-static-1.0/libmongoc-static-1.0-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/libmongoc-static-1.0/libmongoc-static-1.0-config-version.cmake""
(rm -f "lib/cmake/libmongoc-static-1.0/libmongoc-static-1.0-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "share/mongo-c-driver/uninstall.sh""
(rm -f "share/mongo-c-driver/uninstall.sh" && printf "\n") || printf " ... not removed\n"
printf "Removing directory "lib\nlib\nlib\nlib\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0\ninclude\nlib/pkgconfig\nlib\nlib/pkgconfig\nlib\nlib/cmake/libbson-1.0\nlib/cmake\nlib\nlib/cmake/libbson-1.0\nlib/cmake\nlib\nlib/cmake/libbson-static-1.0\nlib/cmake\nlib\nlib/cmake/libbson-static-1.0\nlib/cmake\nlib\nlib\nlib\nlib\nlib\nlib\nlib\nlib\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0\ninclude\nlib/pkgconfig\nlib\nlib/pkgconfig\nlib\nlib/pkgconfig\nlib\nlib/cmake/libmongoc-1.0\nlib/cmake\nlib\nlib/cmake/libmongoc-1.0\nlib/cmake\nlib\nlib/cmake/libmongoc-static-1.0\nlib/cmake\nlib\nlib/cmake/libmongoc-static-1.0\nlib/cmake\nlib\nshare/mongo-c-driver\nshare\n""
(rmdir "lib\nlib\nlib\nlib\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0/bson\ninclude/libbson-1.0\ninclude\ninclude/libbson-1.0\ninclude\nlib/pkgconfig\nlib\nlib/pkgconfig\nlib\nlib/cmake/libbson-1.0\nlib/cmake\nlib\nlib/cmake/libbson-1.0\nlib/cmake\nlib\nlib/cmake/libbson-static-1.0\nlib/cmake\nlib\nlib/cmake/libbson-static-1.0\nlib/cmake\nlib\nlib\nlib\nlib\nlib\nlib\nlib\nlib\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0/mongoc\ninclude/libmongoc-1.0\ninclude\ninclude/libmongoc-1.0\ninclude\nlib/pkgconfig\nlib\nlib/pkgconfig\nlib\nlib/pkgconfig\nlib\nlib/cmake/libmongoc-1.0\nlib/cmake\nlib\nlib/cmake/libmongoc-1.0\nlib/cmake\nlib\nlib/cmake/libmongoc-static-1.0\nlib/cmake\nlib\nlib/cmake/libmongoc-static-1.0\nlib/cmake\nlib\nshare/mongo-c-driver\nshare\n" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
cd ..
printf "Removing top-level installation directory: "/opt/splunk-home/""
(rmdir "/opt/splunk-home/" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"

# Return to the directory from which the program was called
cd ${save_pwd}
